version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: vto-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: virtual_try_on
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend FastAPI service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vto-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=virtual_try_on
      - JWT_SECRET=production-change-this-secret
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - UPLOAD_DIR=uploads
      - MAX_UPLOAD_SIZE=10485760
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
  backend_uploads: